#!/bin/bash

DIR=$(dirname $(readlink -f $0))
SCRIPT=$DIR/$(basename $0)
RCMP=$DIR/rcmp

case "$1" in
    start)
        $RCMP &
        ;;
    stop)
        kill $(cat rcmp.pid)
        ;;
    restart)
        $SCRIPT stop
        $SCRIPT start
        ;;
    update)
        git pull
        $SCRIPT restart
        ;;
esac
