#!/bin/bash

DIR=$(dirname $(readlink -f $0))
SCRIPT=$DIR/$(basename $0)
RCMP=$DIR/rcmp
PIDFILE=$DIR/rcmp.pid

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "RCMP is already running"
        else
            $RCMP &
        fi
        ;;
    stop)
        kill $(cat $PIDFILE)
        rm $PIDFILE
        ;;
    restart)
        $SCRIPT stop
        $SCRIPT start
        ;;
    update)
        git pull
        $SCRIPT restart
        ;;
esac
